In [29]:
pip install gym

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import gym
env = gym . make ("CartPole-v1")

In [3]:
### Check State
env . observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [4]:
### Check Action
for action in range ( env . action_space . n ):
    print(action)

0
1


In [5]:
#the pole 's starting state :
env . reset ()

(array([-0.04448831,  0.01657243,  0.00870515,  0.01066568], dtype=float32),
 {})

In [6]:
### Take Action
env . step ( action =0 )
# return : obs/ next state , reward , terminated , truncated , info

C:\Users\Student\Desktop\INT421\015\env_ml\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


(array([-0.04415686, -0.17867328,  0.00891847,  0.30608243], dtype=float32),
 1.0,
 False,
 False,
 {})

In [7]:
env . step ( action =0 )

(array([-0.04773033, -0.3739212 ,  0.01504012,  0.60156465], dtype=float32),
 1.0,
 False,
 False,
 {})

In [8]:
env . step ( action =1 )

(array([-0.05520875, -0.1790128 ,  0.02707141,  0.31365675], dtype=float32),
 1.0,
 False,
 False,
 {})

In [9]:
### Policy : Random Movement
import gym
env = gym . make ("CartPole-v1")

env . reset ()
for i in range ( 20 ):
    action = env . action_space . sample ()
    observation , reward , terminated , truncated , info = env . step ( action )
    print ("step", i ,"action", action , observation , reward , terminated , info )

step 0 action 0 [ 0.00668183 -0.24455364  0.03265388  0.27654716] 1.0 False {}
step 1 action 0 [ 0.00179075 -0.44012588  0.03818482  0.57934767] 1.0 False {}
step 2 action 0 [-0.00701176 -0.63576156  0.04977177  0.8838109 ] 1.0 False {}
step 3 action 0 [-0.019727   -0.83152276  0.06744799  1.191716  ] 1.0 False {}
step 4 action 0 [-0.03635745 -1.0274506   0.09128231  1.5047541 ] 1.0 False {}
step 5 action 0 [-0.05690646 -1.2235538   0.12137739  1.824484  ] 1.0 False {}
step 6 action 0 [-0.08137754 -1.4197958   0.15786707  2.1522787 ] 1.0 False {}
step 7 action 1 [-0.10977346 -1.2265394   0.20091264  1.9122192 ] 1.0 False {}
step 8 action 0 [-0.13430424 -1.4231808   0.23915702  2.25992   ] 1.0 True {}
step 9 action 1 [-0.16276786 -1.2309684   0.28435543  2.049451  ] 0.0 True {}
step 10 action 1 [-0.18738723 -1.0396602   0.32534444  1.8564911 ] 0.0 True {}
step 11 action 0 [-0.20818043 -1.236579    0.36247426  2.2303464 ] 0.0 True {}
step 12 action 0 [-0.232912  -1.4329284  0.4070812  2.

C:\Users\Student\Desktop\INT421\015\env_ml\Lib\site-packages\gym\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


In [10]:
### Render: CartPole
import gym
# env = gym. make ("CartPole-v1")
env = gym . make ("CartPole-v1", render_mode ="human")
env . reset()
for i in range ( 100 ):
    env . render ()
    action = env . action_space . sample ()
    observation , reward , terminated , info , _ = env . step ( action )
    # print (" step " , i, " action ", action , observation , reward , terminated , info )
env . close ()


In [5]:
import gym
from PIL import Image
env = gym . make ("CartPole-v1", render_mode ='rgb_array')
env . reset ()
screen = env . render ()
images = [ Image . fromarray ( screen )]
for i in range ( 200 ):
    action = env . action_space . sample ()
    observation , reward , terminated , truncated , info = env . step ( action )
    # print ("step", i , "action", action , observation , reward , terminated , info )
    screen = env . render ()
    images . append ( Image . fromarray ( screen ) )
env . close ()
image_file = 'cartpole-v1.gif'
# loop =0: loop forever , duration =1: play each frame for 1ms
images [0]. save ( image_file , save_all =True , append_images = images [1:], loop =1 ,
duration =1 )

In [11]:
### Episode
import gym
env = gym . make ("CartPole-v1")
for episode in range (1 , 11 ):
    score = 0
    state = env . reset ()
    terminated = False
    
    while not terminated :
        action = env . action_space . sample ()
        n_state , reward , terminated , truncated , info = env . step ( action )
        score += reward
    print ('Episode :', episode , 'Score :', score )
env . close ()

Episode : 1 Score : 25.0
Episode : 2 Score : 12.0
Episode : 3 Score : 17.0
Episode : 4 Score : 18.0
Episode : 5 Score : 18.0
Episode : 6 Score : 12.0
Episode : 7 Score : 28.0
Episode : 8 Score : 19.0
Episode : 9 Score : 21.0
Episode : 10 Score : 11.0


In [23]:
### Policy: Agent Training
# https :// stable - baselines3 . readthedocs .io/en/ master / modules / ppo. html
from stable_baselines3 import PPO
from stable_baselines3 . common . vec_env import DummyVecEnv
from stable_baselines3 . common . evaluation import evaluate_policy
import gym
env = gym . make ("CartPole-v1")
env = DummyVecEnv ([lambda : env])
model = PPO ('MlpPolicy', env , verbose =1 )
model . learn ( total_timesteps = 20000 )
model . save ('cartpole_ppo_model')
env . close ()

C:\Users\Student\Desktop\INT421\015\env_ml\Lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


Using cpu device
-----------------------------
| time/              |      |
|    fps             | 2375 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 1065        |
|    iterations           | 2           |
|    time_elapsed         | 3           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009648325 |
|    clip_fraction        | 0.12        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.685      |
|    explained_variance   | -0.00041    |
|    learning_rate        | 0.0003      |
|    loss                 | 5.91        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0191     |
|    value_loss           | 53.2        |
-----------------------------------------
-----------------

In [13]:
import gymnasium as gym
from stable_baselines3 import DQN
env = gym . make ("CartPole-v1", render_mode ="human")
model = DQN ("MlpPolicy", env , verbose =1 )
model . learn ( total_timesteps =10000 , log_interval =4 )
model . save ("dqn_cartpole")
env . close ()

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 24.2     |
|    ep_rew_mean      | 24.2     |
|    exploration_rate | 0.908    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 33       |
|    time_elapsed     | 2        |
|    total_timesteps  | 97       |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 27.4     |
|    ep_rew_mean      | 27.4     |
|    exploration_rate | 0.792    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 40       |
|    time_elapsed     | 5        |
|    total_timesteps  | 219      |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 28.9     |
|    ep_rew_mean      | 28.9   

In [9]:
### Agent evaluation
from stable_baselines3 import PPO
from stable_baselines3 . common . evaluation import evaluate_policy
import gym
env = gym . make ("CartPole-v1", render_mode ="human")
model = PPO . load ('cartpole_ppo_model')
mean_rw , sd_rw = evaluate_policy ( model , env , n_eval_episodes =10 , render =
True )
print ('Reward : Mean', mean_rw , 'SD', sd_rw )
# Returns : Mean reward per episode , std of reward per episode
env.close()

C:\Users\Student\Desktop\INT421\015\env_ml\Lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(
C:\Users\Student\Desktop\INT421\015\env_ml\Lib\site-packages\stable_baselines3\common\evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
C:\Users\Student\Desktop\INT421\015\env_ml\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Reward : Mean 500.0 SD 0.0


In [ ]:
### Agent Testing
import gymnasium as gym
from stable_baselines3 import DQN
env = gym . make ("CartPole-v1", render_mode ="human")

model = DQN.load ("dqn_cartpole")
obs , info = env . reset ()

while True :
    action , _states = model . predict ( obs , deterministic = True )
    obs , reward , terminated , truncated , info = env . step ( action )
    if terminated or truncated :
        obs , info = env . reset ()
env.close()

In [1]:
import gymnasium as gym
from stable_baselines3 import PPO
from PIL import Image
env = gym . make ("CartPole-v1", render_mode ='rgb_array')
model = PPO . load ("cartpole_ppo_model")

obs , info = env . reset ()
screen = env . render ()
images = [Image . fromarray ( screen )]

terminated = False
while not terminated:
    # action = env . action_space . sample ()
    # observation , reward , terminated , truncated , info = env . step ( action )
    action , _states = model . predict ( obs , deterministic = True )
    obs , reward , terminated , truncated , info = env . step ( action )
    # print ("step", i , "action", action , observation , reward , terminated , info )
    screen = env . render ()
    images . append ( Image . fromarray ( screen ) )
env . close ()
image_file = '63130500102-cartpole-v1.gif'
# loop =0: loop forever , duration =1: play each frame for 1ms
images [0]. save ( image_file , save_all =True , append_images = images [1:], loop =1 ,
duration =10 )